website/models.py
# Import necessary modules
from . import db  # from . is equivalent to from website, so anything in this package can be imported
from flask_login import UserMixin
from sqlalchemy.sql import func

# Define the User class, which inherits from db.Model and UserMixin
class User(db.Model, UserMixin):
    # Define class attributes as columns in the database table
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    min_wave_height = db.Column(db.Integer)
    max_wave_height = db.Column(db.Integer)
    max_wind_mph = db.Column(db.Integer)
    min_water_temp = db.Column(db.Integer)

website/__init__.py
# Import necessary modules and classes
from flask import Flask
from flask_apscheduler import APScheduler
from flask_sqlalchemy import SQLAlchemy
from os import path 
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_mail import Mail

# Initialize the SQLAlchemy database instance
db = SQLAlchemy()
DB_NAME = "database.db"

# Function to create the Flask application
def create_app():
    app = Flask(__name__)  # Create a Flask application instance (__name__ represents the current file)

    scheduler = APScheduler()
    scheduler.init_app(app)

    # Add other schedulers if needed
    from surfEmail import send_emails as surf_send_emails  # Rename to avoid confusion
    scheduler.add_job(id="send_emails", func=surf_send_emails, trigger="cron", hour=16, minute=41)
    # Start the scheduler
    print("loaded scheduler")
    scheduler.start()

    # Set Flask application configurations
    app.config['SECRET_KEY'] = 'parkerj25'  # Set the secret key for session security
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'  # Set the URI for the SQLite database
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['MAIL_SERVER'] = 'smtp.gmail.com'  # Set the mail server for Flask-Mail
    app.config['MAIL_PORT'] = 587  # Set the mail server port for Flask-Mail
    app.config['MAIL_USE_TLS'] = True  # Use TLS for Flask-Mail
    app.config['MAIL_USERNAME'] = 'parkerstephenson00@gmail.com'  # Set the email username for Flask-Mail
    app.config['MAIL_PASSWORD'] = 'ahgp vnbn mvlz cdju'  # Set the email password for Flask-Mail
    app.config['MAIL_DEFAULT_SENDER'] = ('Parker Stephenson', 'parkerstephenson@gmail.com')  # Set the default sender for Flask-Mail
    mail = Mail(app)  # Initialize Flask-Mail

    # Initialize SQLAlchemy with the Flask application instance
    db.init_app(app)

    # Initialize Flask-Migrate with the Flask application and SQLAlchemy database instance
    migrate = Migrate(app, db) 

    # Import and register blueprints for different parts of the application
    from.views import views
    from.auth import auth
    #from.surfEmail import surfEmail
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    #app.register_blueprint(surfEmail, url_prefix='/')

    # Import the User model from the models module
    from .models import User 

    # Initialize Flask-Login
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'  # Set the login view for Flask-Login
    login_manager.init_app(app)

    # Define a user loader function for Flask-Login
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    # Return the configured Flask application
    return app

# Function to create the database if it does not exist
def create_database(app):
    if not path.exists('website/' + DB_NAME):  # Check if the database file exists
        with app.app_context():
            db.create_all()  # Create all tables in the database
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

# Create a Blueprint named 'auth' to organize and modularize your authentication routes
auth = Blueprint('auth', __name__)

# Route for user login
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        data = request.form
        print(data)
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again,', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("login.html", user=current_user)

# Route for user logout
@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

# Route for user sign-up
@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        min_wave_height = request.form.get('min_wave_height')
        max_wave_height = request.form.get('max_wave_height')
        max_wind_mph = request.form.get('max_wind_mph')
        min_water_temp = request.form.get('min_water_temp')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        if len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2: 
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            # Create a new user and add to the database
            new_user = User(email=email, first_name=first_name,
                            password=generate_password_hash(password1, method='sha256'),
                            min_wave_height=min_wave_height, max_wave_height=max_wave_height,
                            max_wind_mph=max_wind_mph, min_water_temp=min_water_temp)
            print(f"New User Data: {new_user.__dict__}")
            db.session.add(new_user)
            db.session.commit()
            # Log in the new user
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))
    return render_template("sign_up.html", user=current_user)

website/views.py
# Import necessary modules
from flask import Blueprint, render_template
from flask_login import login_required, current_user

# Create a Blueprint named 'views'
views = Blueprint('views', __name__)

# Define route for the homepage '/'
@views.route('/')
@login_required  # Require the user to be logged in to access this route
def home():
    return render_template("home.html", user=current_user)

# Define route for the 'about' page
@views.route('/about')
@login_required  # Require the user to be logged in to access this route
def about():
    return render_template("about.html", user=current_user)

# Define route for the 'sign_up' page
@views.route('/sign_up')
def sign_up():
    return render_template("sign_up.html", user=current_user)

website/templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/about.css') }}">
    <title>About Us</title>
</head>
<body>

    <section class="about-section">
        <div class="text-section">
            <h2>My Story</h2>
            <p>I founded Surf or Sleep due to the frustrating inconsistencies in surf conditions reported by 
              various websites. Learning to surf, I encountered conflicting data that didn't match the actual 
              conditions when I hit the waves. Month after month, the struggle persisted. Determined to create 
              a solution, Surf or Sleep was born. It's a platform that emerged from the need for reliable and 
              consistent surf data, ensuring a better surfing experience for enthusiasts like me.</p>
        </div>
        <div class="image-section">
            <img src="{{ url_for('static', filename='images/ourStory.jpg') }}" alt="Our Story Image">
        </div>
    </section>

    <section class="about-section">
        <div class="image-section">
            <img src="{{ url_for('static', filename='images/ourObjective.jpg') }}" alt="Our Objective Image">
        </div>
        <div class="text-section">
            <h2>My Objective</h2>
            <p>When creating Surf or Sleep, I had three key objectives. First, I aimed to aggregate surf conditions 
              from various sites, creating a consensus by averaging them out. Second, I wanted to provide a daily 
              email to users at 6 am, empowering them to decide whether to surf or sleep based on the latest 
              conditions. Lastly, I envisioned a personalized experience by considering each user's preferences 
              and matching them with the daily surf conditions. This way, our daily emails offer 
              tailored recommendations telling each use if they should Surf or Sleep.
            </p>
        </div>
    </section>

    <section class="about-section">
      <div class="text-section">
          <h2>My Goals</h2>
          <p>As the beta version of our website unfolds, we have ambitious goals set for its full development. 
              By the end of 2024, our primary objectives include:</p>
          <ul>
              <li><strong>Expanded Surf Conditions:</strong> Extend surf condition coverage beyond Huntington Beach. 
                  Anticipate updates for Newport Beach, Doheney, and Trestles to provide a comprehensive overview 
                  of Orange County conditions.</li>
              <li><strong>User Account Features:</strong> Introduce a dedicated account tab, empowering users to 
                  personalize their site settings and adjust preferences as they progress in their surfing journey.</li>
              <li><strong>UI Enhancements:</strong> Implement ongoing UI enhancements to ensure a consistently improved 
                  user experience. Our commitment is to make regular updates, refining and optimizing the website interface 
                  for seamless navigation.</li>
          </ul>
      </div>
      <div class="image-section">
          <img src="{{ url_for('static', filename='images/ourGoals.jpg') }}" alt="Our Goals Image">
      </div>
  </section>
  
</body>
</html>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <style>
      .navbar-light .navbar-nav .nav-link {
        color: black; 
        text-decoration: none; 
        font-family: 'Inter', sans-serif; 
        font-size: 1.2rem; 
      }

      .navbar-dark .navbar-toggler-icon {
        background-color: white; 
      }

      .navbar-dark .navbar-toggler {
        border: 1px solid white; 
      }

      .navbar-brand {
        margin-right: 0; 
      }

      .navbar-nav {
        width: 100%;
        display: flex;
        justify-content: space-between;
      }

      .navbar-nav .nav-item {
        flex: 1;
        text-align: center;
      }
    </style>

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            <a class="nav-item nav-link" id="home" href="{{ url_for('views.home') }}">Home</a>
            <a class="nav-item nav-link" id="about" href="{{ url_for('views.about') }}">About</a>
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" height="50">
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            <a class="nav-item nav-link" id="sign_up" href="{{ url_for('views.sign_up') }}"> Sign Up</a>
          </div>
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <title>Welcome to Surf or Sleep!</title>
</head>
<body>

    <div class="section" id="home">
        <h1 class="page-title">Welcome to Surf or Sleep,</h1>

        <p class="page-slogan">Helping you make one less decision each day</p>

        <a href="{{ url_for('views.about') }}" class="learn-more-button">Learn More</a>
    </div>
</body>
</html>
{% endblock %}
<script src="{{ url_for('static', filename='js/script.js') }}"></script>

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sign_up.css') }}">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/>

    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password"/>
        
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sign_up.css') }}">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/>

    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="type" class="form-control" id="firstName" name="firstName" placeholder="Enter first name"/>
        
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password"/>
        
    </div>
    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password"/>
    </div>
    <h3 align="center">Input Condition Preferences</h3>
    <div class="form-group">
        <label for="min_wave_height">Minimum Wave Height</label>
        <input type="text" class="form-control" id="min_wave_height" name="min_wave_height" placeholder="Enter minimum wave height"/>
    </div>
    <div class="form-group">
        <label for="max_wave_height">Maximum Wave Height</label>
        <input type="text" class="form-control" id="max_wave_height" name="max_wave_height" placeholder="Enter maximum wave height"/>
    </div>
    <div class="form-group">
        <label for="max_wind_mph">Max Wind MPH</label>
        <input type="text" class="form-control" id="max_wind_mph" name="max_wind_mph" placeholder="Enter max wind MPH"/>
    </div>
    <div class="form-group">
        <label for="min_water_temp">Minimum Water Temperature</label>
        <input type="text" class="form-control" id="min_water_temp" name="min_water_temp" placeholder="Enter minimum water temperature"/>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
 <head>
   <meta charset="utf-8">
   <title>Flask Parent Template</title>
   <link rel="stylesheet" href="{{ url_for('static',     filename='css/template.css') }}">
 </head>
 <body>
    <header>
      <div class="container">
        <h1 class="logo">First Web App</h1>
        <strong><nav>
          <ul class="menu">
            <li><a href="{{ url_for('home') }}">Home</a></li>
            <li><a href="{{ url_for('about') }}">About</a></li>
          </ul>
        </nav></strong>
      </div>
    </header>
    
    {% block content %}
    {% endblock %}
    
 </body>
</html>